### ISSUE TITLE
AutoDetect TimeZone

### ISSUE THREAD

**Issue by thealphadollar** [thealphadollar/send_event_invites#1]
Currently, the timezone is fixed to `Asia/Kolkata`

Python offers to get system timezone in short form such as `IST`.
We can create a database linking timezones to their standard forms and then implement the features.

We can use pytz, and link all timezone function to list all timezones in long.

**Comment by themousepotato** [comment]
I tried generating a dict using the following code segment. But, getting wrong output. Have a look:

import pytz

for zone in pytz.all_timezones:
....tz =pytz. timezone(zone)
....loc_dt = tz.localize(datetime.now())
....db[loc_dt.strftime('%Z')] = zone

**Comment by thealphadollar** [comment]
The first response at the below link has been tested by me :D

https://stackoverflow.com/questions/5946499/how-to-get-the-common-name-for-a-pytz-timezone-eg-est-edt-for-america-new-york

Below is the output I get. It is not always a timezone and hence, we should implement the feature that if it's a time offset, we append it directly to the calendar which can be done through the API.

![screenshot from 2018-06-04 22-33-28](https://user-images.githubusercontent.com/32812320/40931209-d96fad42-6847-11e8-8244-24e09723703a.png)

**Comment by thealphadollar** [comment]
@TheMousePotato `get_localzone()` API endpoint of [tzlocal module](https://github.com/regebro/tzlocal) provides the timezone in full format as Google Calendar uses. It's just a two-line fix then, no need of any dictionary :D

**Comment by thealphadollar** [comment]
Closed via #8 

@TheMousePotato put `fixes #[ISSUE NUMBER]` in PR message to close issues directly with PR.

**Comment by themousepotato** [comment]
@thealphadollar Don't forget to update requirements.txt and corresponding
files.

**Comment by thealphadollar** [comment]
Done.
